spring.application.name=airbnb

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/airbnb_db
spring.datasource.username=root
spring.datasource.password=test

jwt.algorithm.key=hhty-wefg-tyghy-tyghy
jwt.issuer=airbnb
jwt.expiry=86400000
